### ISSUE TITLE
week12 chat client finished

### ISSUE THREAD

**Issue by edodson-matc** [madisoncollege-it-programs/python-scripting-edodson-matc#12]

**Comment by cethenmc** [comment]
The Chat:  Not docking points for this, but the listener should remain listening in case someone else or you want to connect.  Not a big deal still full credit earned.

The FileTransfer.  In the future, please use a relative path in the working directory.  I don't have your full path on my machine, so it causes an inconvenience when grading.  Also, I believe the intention was for the client to read and the server to write.  However, you proved a similar functionality touching on all of the points, so full credit earned.

**Total 8 out of 8, but please be careful on the final to follow the instructions carefully!**
