### ISSUE TITLE
Week 3 assignment ready for grading

### ISSUE THREAD

**Issue by edodson-matc** [madisoncollege-it-programs/python-scripting-edodson-matc#3]

**Comment by cethenmc** [comment]
Evan - Please make it command line executable today, so I can record a grade.  Thanks.  ~Chris

**Comment by cethenmc** [comment]
Hi, Evan.  This one, too, is not executable at the command line.  As I mentioned in the other Issue, I did a fresh git pull.

**Comment by cethenmc** [comment]
You added the space between brackets on the one line, but not on the one with all of the dollar signs.  No worries.  I am letting that on slide.  Full credit achieved.  Thanks for getting all of these in today!  ~Chris
