### ISSUE TITLE
midterm - if-midterm.py is ready

### ISSUE THREAD

**Issue by edodson-matc** [madisoncollege-it-programs/python-scripting-edodson-matc#6]

**Comment by cethenmc** [comment]
All concepts you used were concepts learned in class, which was nice to see.  I assume you could not recall a method to extract the line number as requested.  As a result of not extracting the line number (what if we placed gaps in the line number column) and converting it to an int (which was a hint to help you know what you might use to extract), you will receive a score of 29/33.
